### ISSUE TITLE
v1.8.0 No longer works for me

### ISSUE THREAD

**Issue by lunafoxx** [zeraye/chess-analysis-firefox-extension#14] opened 2024-08-03 06:18 UTC
As the title says. v1.8.0 doesn't work at all for me. When clicking the icon in the address bar, simply nothing happens. However, reverting to v1.7.3 causes the extension to once again work normally.

I am on Windows Firefox version 128.0.3 (64-bit). It is not a specific game that doesn't work, but all games. I don't have any other extensions that would interfere. I can't really give any more info other than that to debug, so if it's still working for you idk what it is about my setup specifically that doesn't work.

**Comment by zeraye** [comment] 2024-08-03 12:05
I'm sorry you're having issue. Will try to reproduce and solve the problem right away

**Comment by zeraye** [comment] 2024-08-03 12:36
I hope this issue was resolved in #15. I already published new version to addons.mozilla.org. Try to update addon version and check if issue still occurs

**Comment by zeraye** [comment] 2024-08-19 21:09
Due to inactivity, I'm closing the issue

**Closed by zeraye** 2024-08-19 21:09 UTC
Labels: bug

**Comment by lunafoxfire** [comment] 2024-08-20 17:59
@zeraye Hello sorry for the delay in communication, but the issue is indeed fixed for me! Thank you for your hard work on this extension!
